version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "juninmd"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 10
